apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shivamgarg-crs.demo.com
spec:
  group: demo.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                email:
                  type: string
              required: ["name", "age", "email"]
          required: ["spec"]
  scope: Namespaced
  names:
    plural: shivamgarg-crs
    singular: shivamgarg-cr
    kind: GetDetail
    shortNames:
    - ct